apiVersion: apps/v1
kind: Deployment

metadata:
  name: rag-app

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: rag-app

  template:
    metadata:
      labels:
        app: rag-app

    spec:
      containers:
      - name: rag-app

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: 8000